#!/usr/bin/env node
/**
 * Downloads the generated sound pack into assets/audio/ and rewrites
 * src/data/audioAssets.ts to require() the local files (bundled, offline,
 * permanent). Run once, on your own machine, within ~24h of the clips being
 * generated (the preview links expire):
 *
 *     node scripts/fetch-audio.mjs
 *
 * Safe to re-run. If a download fails (links lapsed), regenerate the clips and
 * update the URLs below, or ask Claude to regenerate the pack.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(root, 'assets', 'audio');
mkdirSync(OUT, { recursive: true });

const CDN = 'https://elevenlabs-mcp-server.ltdrops.workers.dev/audio';
const FILES = {
  music: `${CDN}/0c794915-f75b-4c52-9c48-36c522eda659.mp3`,
  jingle: `${CDN}/21918505-470a-4448-9c87-4d4fb0291789.mp3`,
  select: `${CDN}/5ab1c5e2-3ecc-4991-9ab4-fa0d62f461aa.mp3`,
  correct: `${CDN}/1bf5f06d-6a98-4714-a6c1-e0e3bd791617.mp3`,
  wrong: `${CDN}/d0122826-51c8-4802-8b24-dd681eab901b.mp3`,
};

let ok = 0;
for (const [key, url] of Object.entries(FILES)) {
  try {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const buf = Buffer.from(await res.arrayBuffer());
    if (buf.length < 500) throw new Error(`suspiciously small (${buf.length} bytes)`);
    writeFileSync(join(OUT, `${key}.mp3`), buf);
    console.log(`  ✓ ${key}.mp3 (${(buf.length / 1024).toFixed(0)} KB)`);
    ok++;
  } catch (e) {
    console.error(`  ✗ ${key}.mp3 — ${e.message}`);
  }
}

if (ok !== Object.keys(FILES).length) {
  console.error(`\nOnly ${ok}/${Object.keys(FILES).length} downloaded. The preview links may have expired — regenerate the pack, then re-run. Leaving audioAssets.ts on the remote URLs.`);
  process.exit(1);
}

const ts = `/**
 * Audio asset registry — BUNDLED (offline). Generated by scripts/fetch-audio.mjs.
 * Keys: music = looping relaxing bed; jingle = win sting; select/correct/wrong
 * = short gameplay SFX.
 */
export type AudioKey = 'music' | 'select' | 'correct' | 'wrong' | 'jingle';

type AudioSrc = number | string | { uri: string };

export const AUDIO: Partial<Record<AudioKey, AudioSrc>> = {
  music: require('../../assets/audio/music.mp3'),
  jingle: require('../../assets/audio/jingle.mp3'),
  select: require('../../assets/audio/select.mp3'),
  correct: require('../../assets/audio/correct.mp3'),
  wrong: require('../../assets/audio/wrong.mp3'),
};
`;
writeFileSync(join(root, 'src', 'data', 'audioAssets.ts'), ts);
console.log('\n✓ Bundled all 5 clips and rewired src/data/audioAssets.ts to require() them.');
console.log('  Restart Expo (npx expo start -c) to pick up the local files.');
