/**
 * Audio asset registry. GENERATED by scripts/fetch-audio.mjs — edit that, not this.
 *
 * Everything is BUNDLED (require()). SFX and voice lines are small and are
 * needed the instant something happens, so a network fetch would arrive after
 * the moment had passed; music is AAC now rather than WAV, which made bundling
 * it affordable too. Nothing in this file touches the network at runtime.
 */
export type AudioKey = 'music' | 'select' | 'correct' | 'wrong' | 'jingle' | 'barajar' | 'pista' | 'grupo' | 'reparto' | 'quitar' | 'reintentar' | 'racha' | 'perdida' | 'tictac';

type AudioSrc = number | string | { uri: string };

export const AUDIO: Partial<Record<AudioKey, AudioSrc>> = {
  select: require('../../assets/audio/select.mp3'),
  correct: require('../../assets/audio/correct.mp3'),
  wrong: require('../../assets/audio/wrong.mp3'),
  jingle: require('../../assets/audio/jingle.mp3'),
  barajar: require('../../assets/audio/barajar.mp3'),
  pista: require('../../assets/audio/pista.mp3'),
  grupo: require('../../assets/audio/grupo.mp3'),
  reparto: require('../../assets/audio/reparto.mp3'),
  quitar: require('../../assets/audio/quitar.mp3'),
  reintentar: require('../../assets/audio/reintentar.mp3'),
  racha: require('../../assets/audio/racha.mp3'),
  perdida: require('../../assets/audio/perdida.mp3'),
  tictac: require('../../assets/audio/tictac.mp3'),
};

/**
 * Celebration voice lines — clips across Mexican, Dominican, Argentine and
 * accent-neutral Spanish voices, so that with a line on every win neither the
 * phrase nor the speaker repeats often. Regionally marked slang is cast only
 * to voices from that region; see scripts/fetch-audio.mjs for the casting.
 * Played at random with no immediate repeat; see src/audio.tsx.
 */
export const VOICE: number[] = [
  require('../../assets/audio/voice/orale.mp3'),
  require('../../assets/audio/voice/andale.mp3'),
  require('../../assets/audio/voice/que_padre.mp3'),
  require('../../assets/audio/voice/muy_bien.mp3'),
  require('../../assets/audio/voice/eso_es.mp3'),
  require('../../assets/audio/voice/que_chulada.mp3'),
  require('../../assets/audio/voice/perfecto.mp3'),
  require('../../assets/audio/voice/lo_lograste.mp3'),
  require('../../assets/audio/voice/vamos.mp3'),
  require('../../assets/audio/voice/excelente.mp3'),
  require('../../assets/audio/voice/asi_se_hace.mp3'),
  require('../../assets/audio/voice/eso.mp3'),
  require('../../assets/audio/voice/que_buena.mp3'),
  require('../../assets/audio/voice/bien_hecho.mp3'),
  require('../../assets/audio/voice/ta_to.mp3'),
  require('../../assets/audio/voice/eso_e_asi.mp3'),
  require('../../assets/audio/voice/que_vaina_buena.mp3'),
  require('../../assets/audio/voice/ta_duro.mp3'),
  require('../../assets/audio/voice/se_formo.mp3'),
  require('../../assets/audio/voice/ta_pila.mp3'),
  require('../../assets/audio/voice/que_chuleria.mp3'),
  require('../../assets/audio/voice/ta_brutal.mp3'),
  require('../../assets/audio/voice/dimelo_campeon.mp3'),
  require('../../assets/audio/voice/que_chido.mp3'),
  require('../../assets/audio/voice/padrisimo.mp3'),
  require('../../assets/audio/voice/ya_la_hiciste.mp3'),
  require('../../assets/audio/voice/te_la_rifaste.mp3'),
  require('../../assets/audio/voice/eso_mero.mp3'),
  require('../../assets/audio/voice/andale_pues.mp3'),
  require('../../assets/audio/voice/que_maquina.mp3'),
  require('../../assets/audio/voice/va_que_va.mp3'),
  require('../../assets/audio/voice/no_inventes.mp3'),
  require('../../assets/audio/voice/que_barbaro.mp3'),
  require('../../assets/audio/voice/sale.mp3'),
  require('../../assets/audio/voice/increible.mp3'),
  require('../../assets/audio/voice/fantastico.mp3'),
  require('../../assets/audio/voice/buenisimo.mp3'),
  require('../../assets/audio/voice/magnifico.mp3'),
  require('../../assets/audio/voice/impecable.mp3'),
  require('../../assets/audio/voice/que_racha.mp3'),
  require('../../assets/audio/voice/campeon.mp3'),
  require('../../assets/audio/voice/lo_hiciste.mp3'),
  require('../../assets/audio/voice/muy_bien_hecho.mp3'),
  require('../../assets/audio/voice/tremendo.mp3'),
  require('../../assets/audio/voice/genial.mp3'),
  require('../../assets/audio/voice/sin_un_error.mp3'),
];

/**
 * Background music — BUNDLED as AAC by scripts/encode-music.mjs.
 *
 * Sixty round beds across fifteen Latin genres, three home beds and ten win
 * fanfares. Every bed is baked into a seamless loop by that script, so it can
 * be played with loop = true and never expose a join.
 *
 * These were streamed as uncompressed WAV, one track per round. At 96 kbps AAC
 * the whole set fits in the bundle, which removes the last per-round audio
 * fetch. With the card deck also bundled, only video still touches the network.
 */
export const MUSIC = {
  home: [
    require('../../assets/music/home.m4a'),
    require('../../assets/music/home2.m4a'),
    require('../../assets/music/home3.m4a'),
  ],
  wins: [
    require('../../assets/music/win.m4a'),
    require('../../assets/music/win2.m4a'),
    require('../../assets/music/win3.m4a'),
    require('../../assets/music/win4.m4a'),
    require('../../assets/music/win5.m4a'),
    require('../../assets/music/win6.m4a'),
    require('../../assets/music/win7.m4a'),
    require('../../assets/music/win8.m4a'),
    require('../../assets/music/win9.m4a'),
    require('../../assets/music/win10.m4a'),
  ],
  rounds: [
    require('../../assets/music/bachata.m4a'),
    require('../../assets/music/bachata2.m4a'),
    require('../../assets/music/bachata3.m4a'),
    require('../../assets/music/bachata4.m4a'),
    require('../../assets/music/reggaeton.m4a'),
    require('../../assets/music/reggaeton2.m4a'),
    require('../../assets/music/reggaeton3.m4a'),
    require('../../assets/music/reggaeton4.m4a'),
    require('../../assets/music/cumbia.m4a'),
    require('../../assets/music/cumbia2.m4a'),
    require('../../assets/music/cumbia3.m4a'),
    require('../../assets/music/cumbia4.m4a'),
    require('../../assets/music/bolero.m4a'),
    require('../../assets/music/bolero2.m4a'),
    require('../../assets/music/bolero3.m4a'),
    require('../../assets/music/bolero4.m4a'),
    require('../../assets/music/son_jarocho.m4a'),
    require('../../assets/music/son_jarocho2.m4a'),
    require('../../assets/music/son_jarocho3.m4a'),
    require('../../assets/music/son_jarocho4.m4a'),
    require('../../assets/music/marimba.m4a'),
    require('../../assets/music/marimba2.m4a'),
    require('../../assets/music/marimba3.m4a'),
    require('../../assets/music/marimba4.m4a'),
    require('../../assets/music/mariachi.m4a'),
    require('../../assets/music/mariachi2.m4a'),
    require('../../assets/music/mariachi3.m4a'),
    require('../../assets/music/mariachi4.m4a'),
    require('../../assets/music/nortena.m4a'),
    require('../../assets/music/nortena2.m4a'),
    require('../../assets/music/nortena3.m4a'),
    require('../../assets/music/nortena4.m4a'),
    require('../../assets/music/banda.m4a'),
    require('../../assets/music/banda2.m4a'),
    require('../../assets/music/banda3.m4a'),
    require('../../assets/music/banda4.m4a'),
    require('../../assets/music/merengue.m4a'),
    require('../../assets/music/merengue2.m4a'),
    require('../../assets/music/merengue3.m4a'),
    require('../../assets/music/merengue4.m4a'),
    require('../../assets/music/huapango.m4a'),
    require('../../assets/music/huapango2.m4a'),
    require('../../assets/music/huapango3.m4a'),
    require('../../assets/music/huapango4.m4a'),
    require('../../assets/music/danzon.m4a'),
    require('../../assets/music/danzon2.m4a'),
    require('../../assets/music/danzon3.m4a'),
    require('../../assets/music/danzon4.m4a'),
    require('../../assets/music/ranchera.m4a'),
    require('../../assets/music/ranchera2.m4a'),
    require('../../assets/music/ranchera3.m4a'),
    require('../../assets/music/ranchera4.m4a'),
    require('../../assets/music/salsa.m4a'),
    require('../../assets/music/salsa2.m4a'),
    require('../../assets/music/salsa3.m4a'),
    require('../../assets/music/salsa4.m4a'),
    require('../../assets/music/trova.m4a'),
    require('../../assets/music/trova2.m4a'),
    require('../../assets/music/trova3.m4a'),
    require('../../assets/music/trova4.m4a'),
  ],
} as const;
