/**
 * Audio asset registry. GENERATED by scripts/fetch-audio.mjs — edit that, not this.
 *
 * SFX and voice lines are BUNDLED (require()): they are small, and both are
 * needed the instant something happens, so a network fetch would arrive after
 * the moment had passed. Music is STREAMED from our own Supabase bucket —
 * those files are megabytes and would bloat the download.
 */
export type AudioKey = 'music' | 'select' | 'correct' | 'wrong' | 'jingle';

type AudioSrc = number | string | { uri: string };

export const AUDIO: Partial<Record<AudioKey, AudioSrc>> = {
  select: require('../../assets/audio/select.mp3'),
  correct: require('../../assets/audio/correct.mp3'),
  wrong: require('../../assets/audio/wrong.mp3'),
  jingle: require('../../assets/audio/jingle.mp3'),
};

/**
 * Celebration voice lines — fourteen clips across eight Spanish voices, so
 * that with a line on every win neither the phrase nor the speaker repeats
 * often. Played at random with no immediate repeat; see src/audio.tsx.
 */
export const VOICE: number[] = [
  require('../../assets/audio/voice/orale.mp3'),
  require('../../assets/audio/voice/andale.mp3'),
  require('../../assets/audio/voice/que_padre.mp3'),
  require('../../assets/audio/voice/muy_bien.mp3'),
  require('../../assets/audio/voice/eso_es.mp3'),
  require('../../assets/audio/voice/que_chulada.mp3'),
  require('../../assets/audio/voice/perfecto.mp3'),
  require('../../assets/audio/voice/lo_lograste.mp3'),
  require('../../assets/audio/voice/vamos.mp3'),
  require('../../assets/audio/voice/excelente.mp3'),
  require('../../assets/audio/voice/asi_se_hace.mp3'),
  require('../../assets/audio/voice/eso.mp3'),
  require('../../assets/audio/voice/que_buena.mp3'),
  require('../../assets/audio/voice/bien_hecho.mp3'),
];

/**
 * Background music — BUNDLED as AAC by scripts/encode-music.mjs.
 *
 * These were 21 MB of uncompressed WAV streamed one track per round. At 128 kbps
 * AAC the whole set is a few MB, so there is no reason to stream them: bundling
 * removes the last per-round audio fetch. With the card deck also bundled, only
 * video still touches the network.
 */
export const MUSIC = {
  home: require('../../assets/music/home.m4a'),
  wins: [
    require('../../assets/music/win.m4a'),
    require('../../assets/music/win2.m4a'),
    require('../../assets/music/win3.m4a'),
    require('../../assets/music/win4.m4a'),
    require('../../assets/music/win5.m4a'),
  ],
  rounds: [
    require('../../assets/music/bachata.m4a'),
    require('../../assets/music/reggaeton.m4a'),
    require('../../assets/music/cumbia.m4a'),
    require('../../assets/music/bolero.m4a'),
    require('../../assets/music/son_jarocho.m4a'),
    require('../../assets/music/marimba.m4a'),
    require('../../assets/music/bachata2.m4a'),
    require('../../assets/music/reggaeton2.m4a'),
    require('../../assets/music/cumbia2.m4a'),
    require('../../assets/music/bolero2.m4a'),
    require('../../assets/music/son_jarocho2.m4a'),
    require('../../assets/music/marimba2.m4a'),
  ],
} as const;
