/**
 * Audio asset registry. GENERATED by scripts/fetch-audio.mjs — edit that, not this.
 *
 * SFX and voice lines are BUNDLED (require()): they are small, and both are
 * needed the instant something happens, so a network fetch would arrive after
 * the moment had passed. Music is STREAMED from our own Supabase bucket —
 * those files are megabytes and would bloat the download.
 */
export type AudioKey = 'music' | 'select' | 'correct' | 'wrong' | 'jingle';

type AudioSrc = number | string | { uri: string };

export const AUDIO: Partial<Record<AudioKey, AudioSrc>> = {
  select: require('../../assets/audio/select.mp3'),
  correct: require('../../assets/audio/correct.mp3'),
  wrong: require('../../assets/audio/wrong.mp3'),
  jingle: require('../../assets/audio/jingle.mp3'),
};

/**
 * Celebration voice lines — fourteen clips across eight Spanish voices, so
 * that with a line on every win neither the phrase nor the speaker repeats
 * often. Played at random with no immediate repeat; see src/audio.tsx.
 */
export const VOICE: number[] = [
  require('../../assets/audio/voice/orale.mp3'),
  require('../../assets/audio/voice/andale.mp3'),
  require('../../assets/audio/voice/que_padre.mp3'),
  require('../../assets/audio/voice/muy_bien.mp3'),
  require('../../assets/audio/voice/eso_es.mp3'),
  require('../../assets/audio/voice/que_chulada.mp3'),
  require('../../assets/audio/voice/perfecto.mp3'),
  require('../../assets/audio/voice/lo_lograste.mp3'),
  require('../../assets/audio/voice/vamos.mp3'),
  require('../../assets/audio/voice/excelente.mp3'),
  require('../../assets/audio/voice/asi_se_hace.mp3'),
  require('../../assets/audio/voice/eso.mp3'),
  require('../../assets/audio/voice/que_buena.mp3'),
  require('../../assets/audio/voice/bien_hecho.mp3'),
];

/**
 * Background music — STREAMED from our own Supabase bucket, as uncompressed
 * WAV averaging 1.2 MB a track.
 *
 * Run scripts/encode-music.mjs to re-encode these to AAC and bundle them; this
 * file is regenerated to require() them and music stops touching the network.
 */
const MUSIC_CDN = 'https://bmybvrqbpachjxrejxdj.supabase.co/storage/v1/object/public/audio';

export const MUSIC = {
  home: `${MUSIC_CDN}/home.wav`,
  wins: [
    `${MUSIC_CDN}/win.wav`,
    `${MUSIC_CDN}/win2.wav`,
    `${MUSIC_CDN}/win3.wav`,
    `${MUSIC_CDN}/win4.wav`,
    `${MUSIC_CDN}/win5.wav`,
  ],
  rounds: [
    `${MUSIC_CDN}/bachata.wav`,
    `${MUSIC_CDN}/reggaeton.wav`,
    `${MUSIC_CDN}/cumbia.wav`,
    `${MUSIC_CDN}/bolero.wav`,
    `${MUSIC_CDN}/son_jarocho.wav`,
    `${MUSIC_CDN}/marimba.wav`,
    `${MUSIC_CDN}/bachata2.wav`,
    `${MUSIC_CDN}/reggaeton2.wav`,
    `${MUSIC_CDN}/cumbia2.wav`,
    `${MUSIC_CDN}/bolero2.wav`,
    `${MUSIC_CDN}/son_jarocho2.wav`,
    `${MUSIC_CDN}/marimba2.wav`,
  ],
} as const;
